package com.boha.sandbox5.models;

public class Constants {

    public static final String
            VEHICLE_LOCATION = "VEHICLE_LOCATION",
            DISPATCH_RECORD = "DISPATCH_RECORD",
            COMMUTER_REQUEST = "COMMUTER_REQUEST",
            VEHICLE_LANDMARK_ARRIVAL = "VEHICLE_LANDMARK_ARRIVAL",
            VEHICLE_LANDMARK_DEPARTURE = "VEHICLE_LANDMARK_DEPARTURE",
            COMMUTER_LANDMARK_ARRIVAL = "COMMUTER_LANDMARK_ARRIVAL",
            COMMUTER_LANDMARK_DEPARTURE = "COMMUTER_LANDMARK_DEPARTURE",
            ROUTE_DISTANCE_ESTIMATION = "ROUTE_DISTANCE_ESTIMATION";
}
